# Generated by Django 3.2.5 on 2021-12-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultApp', '0009_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='logindetails',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
