# Generated by Django 3.2.9 on 2022-01-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultApp', '0011_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
